In [1]:
import pandas as pd

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_data = pd.ExcelFile("crowdfunding.xlsx")
# Get the sheet names.
crowdfunding_data.sheet_names

['crowdfunding_info', 'contact_info']

In [3]:
crowdfunding_info_df = pd.read_excel(crowdfunding_data, sheet_name='crowdfunding_info')
crowdfunding_info_df

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks
996,2031,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays
997,1627,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays
998,2175,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock
999,1788,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks

In [5]:
# Get the contact_info from the contact_info worksheet.
# Increase the width of the column.
pd.set_option('max_colwidth', 400)
contact_info_df = pd.read_excel(crowdfunding_data, sheet_name='contact_info', header=2)
contact_info_df.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

In [6]:
# Get a brief summary of the crowdfunding_info DataFrame. 
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   company_name             1000 non-null   object
 2   blurb                    1000 non-null   object
 3   goal                     1000 non-null   int64
 4   pledged                  1000 non-null   int64
 5   outcome                  1000 non-null   object
 6   backers_count            1000 non-null   int64
 7   country                  1000 non-null   object
 8   currency                 1000 non-null   object
 9   launched_at              1000 non-null   int64
 10  deadline                 1000 non-null   int64
 11  staff_pick               1000 non-null   bool
 12  spotlight                1000 non-null   bool
 13  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(6), object(6)
memory usage: 95.8+ KB

In [7]:
# Get a brief summary of the contact_info DataFrame. 
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           1001 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB